### ISSUE TITLE
command to give amount of study course specific members

### ISSUE THREAD

**Issue by Rec0gnice** [FHA-FB5/DC-Universe#46]

**Comment by TitusKirch** [comment]
Is it about the number of members on the whole server? You can see that in Discord anyway and this info is irrelevant (since it's only important how many are participating in a Grupopenphase)

**Comment by Rec0gnice** [comment]
But it is a nice feature for other people

**Comment by TitusKirch** [comment]
yes, but in the worst case every get function (if the user or the role is not capped) is an event. With over 400 people, it will be fun.

Who is the feature aimed at?
