### ISSUE TITLE
Automatic deletion of the !poll message

### ISSUE THREAD

**Issue by TitusKirch** [FHA-FB5/DC-Universe#49]
What do you think @Rec0gnice ?

**Comment by Rec0gnice** [comment]
I can do that would be nice to have, but I can imagine that it can be useful to keep old polls for reference. Also Ich would also need to store the message id in the db then and have to reference it somehow

**Comment by TitusKirch** [comment]
No you don't have to, you can delete the message above the ctx. Right here: https://github.com/FHA-FB5/DC-Universe/blob/main/extensions/polls.py#L75

**Comment by TitusKirch** [comment]
N/A
